/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationsIndexRouteImport } from './routes/automations.index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as AutomationsAutomationIdRouteImport } from './routes/automations.$automationId'
import { Route as AutomationsSessionsIdRouteImport } from './routes/automations.sessions.$id'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutomationsRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsAutomationIdRoute = AutomationsAutomationIdRouteImport.update({
  id: '/$automationId',
  path: '/$automationId',
  getParentRoute: () => AutomationsRoute,
} as any)
const AutomationsSessionsIdRoute = AutomationsSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/connectors': typeof ConnectorsRoute
  '/usage': typeof UsageRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/session/$id': typeof SessionIdRoute
  '/automations/': typeof AutomationsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/usage': typeof UsageRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/session/$id': typeof SessionIdRoute
  '/automations': typeof AutomationsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/connectors': typeof ConnectorsRoute
  '/usage': typeof UsageRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/session/$id': typeof SessionIdRoute
  '/automations/': typeof AutomationsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/connectors'
    | '/usage'
    | '/automations/$automationId'
    | '/session/$id'
    | '/automations/'
    | '/automations/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/usage'
    | '/automations/$automationId'
    | '/session/$id'
    | '/automations'
    | '/automations/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/connectors'
    | '/usage'
    | '/automations/$automationId'
    | '/session/$id'
    | '/automations/'
    | '/automations/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRouteWithChildren
  ConnectorsRoute: typeof ConnectorsRoute
  UsageRoute: typeof UsageRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/': {
      id: '/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof AutomationsRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/$automationId': {
      id: '/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AutomationsAutomationIdRouteImport
      parentRoute: typeof AutomationsRoute
    }
    '/automations/sessions/$id': {
      id: '/automations/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/automations/sessions/$id'
      preLoaderRoute: typeof AutomationsSessionsIdRouteImport
      parentRoute: typeof AutomationsRoute
    }
  }
}

interface AutomationsRouteChildren {
  AutomationsAutomationIdRoute: typeof AutomationsAutomationIdRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  AutomationsSessionsIdRoute: typeof AutomationsSessionsIdRoute
}

const AutomationsRouteChildren: AutomationsRouteChildren = {
  AutomationsAutomationIdRoute: AutomationsAutomationIdRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  AutomationsSessionsIdRoute: AutomationsSessionsIdRoute,
}

const AutomationsRouteWithChildren = AutomationsRoute._addFileChildren(
  AutomationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRouteWithChildren,
  ConnectorsRoute: ConnectorsRoute,
  UsageRoute: UsageRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
