/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings.index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as RecordingsIdRouteImport } from './routes/recordings.$id'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/connectors': typeof ConnectorsRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/recordings/': typeof RecordingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/connectors': typeof ConnectorsRoute
  '/usage': typeof UsageRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/recordings': typeof RecordingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/connectors': typeof ConnectorsRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/recordings/': typeof RecordingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/connectors'
    | '/recordings'
    | '/usage'
    | '/recordings/$id'
    | '/session/$id'
    | '/recordings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/connectors'
    | '/usage'
    | '/recordings/$id'
    | '/session/$id'
    | '/recordings'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/connectors'
    | '/recordings'
    | '/usage'
    | '/recordings/$id'
    | '/session/$id'
    | '/recordings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  ConnectorsRoute: typeof ConnectorsRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
  }
}

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  ConnectorsRoute: ConnectorsRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  UsageRoute: UsageRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
