/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as AutomationsRouteRouteImport } from './routes/automations/route'
import { Route as AgendaRouteRouteImport } from './routes/agenda/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as AutomationsIndexRouteImport } from './routes/automations/index'
import { Route as AgendaIndexRouteImport } from './routes/agenda/index'
import { Route as SessionIdRouteImport } from './routes/session.$id'
import { Route as RecordingsIdRouteImport } from './routes/recordings/$id'
import { Route as AutomationsAutomationIdRouteImport } from './routes/automations/$automationId'
import { Route as AgendaListIdRouteImport } from './routes/agenda/$listId'
import { Route as AutomationsSessionsIdRouteImport } from './routes/automations/sessions/$id'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRouteRoute = AutomationsRouteRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRouteRoute = AgendaRouteRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecordingsRoute,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutomationsRouteRoute,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgendaRouteRoute,
} as any)
const SessionIdRoute = SessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIdRoute = RecordingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordingsRoute,
} as any)
const AutomationsAutomationIdRoute = AutomationsAutomationIdRouteImport.update({
  id: '/$automationId',
  path: '/$automationId',
  getParentRoute: () => AutomationsRouteRoute,
} as any)
const AgendaListIdRoute = AgendaListIdRouteImport.update({
  id: '/$listId',
  path: '/$listId',
  getParentRoute: () => AgendaRouteRoute,
} as any)
const AutomationsSessionsIdRoute = AutomationsSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AutomationsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRouteRouteWithChildren
  '/automations': typeof AutomationsRouteRouteWithChildren
  '/connectors': typeof ConnectorsRoute
  '/memories': typeof MemoriesRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/agenda/$listId': typeof AgendaListIdRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRoute
  '/memories': typeof MemoriesRoute
  '/usage': typeof UsageRoute
  '/agenda/$listId': typeof AgendaListIdRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/agenda': typeof AgendaIndexRoute
  '/automations': typeof AutomationsIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRouteRouteWithChildren
  '/automations': typeof AutomationsRouteRouteWithChildren
  '/connectors': typeof ConnectorsRoute
  '/memories': typeof MemoriesRoute
  '/recordings': typeof RecordingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/agenda/$listId': typeof AgendaListIdRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRoute
  '/recordings/$id': typeof RecordingsIdRoute
  '/session/$id': typeof SessionIdRoute
  '/agenda/': typeof AgendaIndexRoute
  '/automations/': typeof AutomationsIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/automations/sessions/$id': typeof AutomationsSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/automations'
    | '/connectors'
    | '/memories'
    | '/recordings'
    | '/usage'
    | '/agenda/$listId'
    | '/automations/$automationId'
    | '/recordings/$id'
    | '/session/$id'
    | '/agenda/'
    | '/automations/'
    | '/recordings/'
    | '/automations/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connectors'
    | '/memories'
    | '/usage'
    | '/agenda/$listId'
    | '/automations/$automationId'
    | '/recordings/$id'
    | '/session/$id'
    | '/agenda'
    | '/automations'
    | '/recordings'
    | '/automations/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/automations'
    | '/connectors'
    | '/memories'
    | '/recordings'
    | '/usage'
    | '/agenda/$listId'
    | '/automations/$automationId'
    | '/recordings/$id'
    | '/session/$id'
    | '/agenda/'
    | '/automations/'
    | '/recordings/'
    | '/automations/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRouteRoute: typeof AgendaRouteRouteWithChildren
  AutomationsRouteRoute: typeof AutomationsRouteRouteWithChildren
  ConnectorsRoute: typeof ConnectorsRoute
  MemoriesRoute: typeof MemoriesRoute
  RecordingsRoute: typeof RecordingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  SessionIdRoute: typeof SessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/automations/': {
      id: '/automations/'
      path: '/'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof AutomationsRouteRoute
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof AgendaRouteRoute
    }
    '/session/$id': {
      id: '/session/$id'
      path: '/session/$id'
      fullPath: '/session/$id'
      preLoaderRoute: typeof SessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/$id': {
      id: '/recordings/$id'
      path: '/$id'
      fullPath: '/recordings/$id'
      preLoaderRoute: typeof RecordingsIdRouteImport
      parentRoute: typeof RecordingsRoute
    }
    '/automations/$automationId': {
      id: '/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AutomationsAutomationIdRouteImport
      parentRoute: typeof AutomationsRouteRoute
    }
    '/agenda/$listId': {
      id: '/agenda/$listId'
      path: '/$listId'
      fullPath: '/agenda/$listId'
      preLoaderRoute: typeof AgendaListIdRouteImport
      parentRoute: typeof AgendaRouteRoute
    }
    '/automations/sessions/$id': {
      id: '/automations/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/automations/sessions/$id'
      preLoaderRoute: typeof AutomationsSessionsIdRouteImport
      parentRoute: typeof AutomationsRouteRoute
    }
  }
}

interface AgendaRouteRouteChildren {
  AgendaListIdRoute: typeof AgendaListIdRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
}

const AgendaRouteRouteChildren: AgendaRouteRouteChildren = {
  AgendaListIdRoute: AgendaListIdRoute,
  AgendaIndexRoute: AgendaIndexRoute,
}

const AgendaRouteRouteWithChildren = AgendaRouteRoute._addFileChildren(
  AgendaRouteRouteChildren,
)

interface AutomationsRouteRouteChildren {
  AutomationsAutomationIdRoute: typeof AutomationsAutomationIdRoute
  AutomationsIndexRoute: typeof AutomationsIndexRoute
  AutomationsSessionsIdRoute: typeof AutomationsSessionsIdRoute
}

const AutomationsRouteRouteChildren: AutomationsRouteRouteChildren = {
  AutomationsAutomationIdRoute: AutomationsAutomationIdRoute,
  AutomationsIndexRoute: AutomationsIndexRoute,
  AutomationsSessionsIdRoute: AutomationsSessionsIdRoute,
}

const AutomationsRouteRouteWithChildren =
  AutomationsRouteRoute._addFileChildren(AutomationsRouteRouteChildren)

interface RecordingsRouteChildren {
  RecordingsIdRoute: typeof RecordingsIdRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
}

const RecordingsRouteChildren: RecordingsRouteChildren = {
  RecordingsIdRoute: RecordingsIdRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
}

const RecordingsRouteWithChildren = RecordingsRoute._addFileChildren(
  RecordingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRouteRoute: AgendaRouteRouteWithChildren,
  AutomationsRouteRoute: AutomationsRouteRouteWithChildren,
  ConnectorsRoute: ConnectorsRoute,
  MemoriesRoute: MemoriesRoute,
  RecordingsRoute: RecordingsRouteWithChildren,
  UsageRoute: UsageRoute,
  SessionIdRoute: SessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
