// Generated by scripts/check-design-system.ts. Do not edit.

export const stackGapVariants = {
  none: 'gap-space-none',
  '2xs': 'gap-space-2xs',
  xs: 'gap-space-xs',
  s: 'gap-space-s',
  m: 'gap-space-m',
  l: 'gap-space-l',
  xl: 'gap-space-xl',
  '2xl': 'gap-space-2xl',
  '3xl': 'gap-space-3xl',
} as const;
export const stackPaddingVariants = {
  none: 'p-space-none',
  '2xs': 'p-space-2xs',
  xs: 'p-space-xs',
  s: 'p-space-s',
  m: 'p-space-m',
  l: 'p-space-l',
  xl: 'p-space-xl',
  '2xl': 'p-space-2xl',
  '3xl': 'p-space-3xl',
} as const;
export const stackDirectionVariants = { row: 'flex-row', column: 'flex-col' } as const;
export const stackAlignVariants = {
  start: 'items-start',
  center: 'items-center',
  end: 'items-end',
  stretch: 'items-stretch',
} as const;
export const stackJustifyVariants = {
  start: 'justify-start',
  center: 'justify-center',
  end: 'justify-end',
  between: 'justify-between',
} as const;
export const stackWrapVariants = { true: 'flex-wrap', false: 'flex-nowrap' } as const;
export const stackGrowVariants = { true: 'min-w-0 flex-1', false: null } as const;
export const stackWidthVariants = { full: 'w-full' } as const;
export const stackHeightVariants = { full: 'h-full' } as const;
export const stackOverflowVariants = {
  hidden: 'overflow-hidden',
  auto: 'overflow-auto',
  'y-auto': 'overflow-y-auto',
} as const;
export const textVariantClasses = {
  micro: 'text-2xs',
  caption: 'text-xs',
  label: 'text-xs font-medium',
  body: 'text-sm',
  'body-strong': 'text-sm font-medium',
  'heading-s': 'text-base font-semibold',
  'heading-m': 'text-xl font-semibold tracking-tight',
  'heading-l': 'text-2xl font-semibold tracking-tight',
  code: 'font-mono text-xs',
  metric: 'text-2xl font-semibold tabular-nums',
} as const;
export const textToneClasses = {
  default: 'text-foreground',
  muted: 'text-muted-foreground',
  faint: 'text-text-faint',
  primary: 'text-primary',
  destructive: 'text-destructive',
  success: 'text-success',
  warning: 'text-warning',
} as const;
export const textAlignClasses = { left: 'text-left', center: 'text-center', right: 'text-right' } as const;
export const textLineClampClasses = { '1': 'line-clamp-1', '2': 'line-clamp-2', '3': 'line-clamp-3' } as const;
export const iconSizeClasses = { xs: 'size-icon-xs', s: 'size-icon-s', m: 'size-icon-m', l: 'size-icon-l' } as const;
