export const designTokens = {
  spacing: {
    none: { value: '0', legacy: ['0'] },
    '2xs': { value: '2px', legacy: ['0.5', '0.75'] },
    xs: { value: '4px', legacy: ['1'] },
    s: { value: '6px', legacy: ['1.5'] },
    m: { value: '8px', legacy: ['2', '2.5'] },
    l: { value: '12px', legacy: ['3', '3.5'] },
    xl: { value: '16px', legacy: ['4', '5'] },
    '2xl': { value: '24px', legacy: ['6'] },
    '3xl': { value: '32px', legacy: ['8', '9', '10', '12', '14', '16', '40'] },
  },
  colors: {
    'border-subtle': 'color-mix(in oklab, var(--border) 55%, transparent)',
    'surface-sunken': 'color-mix(in oklab, var(--muted) 25%, transparent)',
    'text-faint': 'color-mix(in oklab, var(--muted-foreground) 45%, transparent)',
    'primary-subtle': 'color-mix(in oklab, var(--primary) 10%, transparent)',
    'destructive-subtle': 'color-mix(in oklab, var(--destructive) 10%, transparent)',
    'success-subtle': 'color-mix(in oklab, var(--success) 10%, transparent)',
    'warning-subtle': 'color-mix(in oklab, var(--warning) 10%, transparent)',
    'info-subtle': 'color-mix(in oklab, var(--info) 10%, transparent)',
  },
  motion: {
    easing: { standard: 'cubic-bezier(0.2, 0, 0, 1)', emphasized: 'cubic-bezier(0.3, 0, 0.8, 0.15)' },
    duration: { fast: '120ms', base: '200ms', slow: '320ms' },
  },
  iconSize: { xs: '12px', s: '14px', m: '16px', l: '20px' },
  primitives: {
    stack: {
      direction: { row: 'flex-row', column: 'flex-col' },
      align: { start: 'items-start', center: 'items-center', end: 'items-end', stretch: 'items-stretch' },
      justify: { start: 'justify-start', center: 'justify-center', end: 'justify-end', between: 'justify-between' },
      wrap: { true: 'flex-wrap', false: 'flex-nowrap' },
    },
    text: {
      variant: {
        micro: 'text-2xs',
        caption: 'text-xs',
        label: 'text-xs font-medium',
        body: 'text-sm',
        'body-strong': 'text-sm font-medium',
        'heading-s': 'text-base font-semibold',
        'heading-m': 'text-xl font-semibold tracking-tight',
        'heading-l': 'text-2xl font-semibold tracking-tight',
        code: 'font-mono text-xs',
        metric: 'text-2xl font-semibold tabular-nums',
      },
      tone: {
        default: 'text-foreground',
        muted: 'text-muted-foreground',
        faint: 'text-text-faint',
        primary: 'text-primary',
        destructive: 'text-destructive',
        success: 'text-success',
        warning: 'text-warning',
      },
    },
  },
  lint: {
    tokenOpacity: {
      'border-border/40': 'border-border-subtle',
      'border-border/50': 'border-border-subtle',
      'border-border/60': 'border-border-subtle',
      'border-border/70': 'border-border-subtle',
      'border-border/80': 'border-border-subtle',
      'bg-border/50': 'bg-border-subtle',
      'bg-border/60': 'bg-border-subtle',
      'divide-border/40': 'divide-border-subtle',
      'bg-muted/10': 'bg-surface-sunken',
      'bg-muted/15': 'bg-surface-sunken',
      'bg-muted/20': 'bg-surface-sunken',
      'bg-muted/25': 'bg-surface-sunken',
      'bg-muted/30': 'bg-surface-sunken',
      'bg-muted/40': 'bg-surface-sunken',
      'bg-muted/50': 'bg-surface-sunken',
      'bg-muted/60': 'bg-surface-sunken',
      'bg-muted/70': 'bg-surface-sunken',
      'bg-card/30': 'bg-card',
      'bg-card/40': 'bg-card',
      'bg-card/50': 'bg-card',
      'bg-card/70': 'bg-card',
      'bg-card/80': 'bg-card',
      'bg-card/95': 'bg-card',
      'bg-background/60': 'bg-background',
      'bg-background/80': 'bg-background',
      'text-muted-foreground/30': 'text-text-faint',
      'text-muted-foreground/40': 'text-text-faint',
      'text-muted-foreground/60': 'text-text-faint',
      'text-muted-foreground/70': 'text-text-faint',
      'text-muted-foreground/80': 'text-text-faint',
      'text-foreground/60': 'text-muted-foreground',
      'text-foreground/80': 'text-foreground',
      'text-foreground/85': 'text-foreground',
      'text-foreground/90': 'text-foreground',
      'text-primary/80': 'text-primary',
      'text-destructive/70': 'text-destructive',
      'text-destructive/80': 'text-destructive',
      'text-destructive/90': 'text-destructive',
      'bg-primary/5': 'bg-primary-subtle',
      'bg-primary/10': 'bg-primary-subtle',
      'bg-primary/20': 'bg-primary-subtle',
      'bg-primary/90': 'brightness-95',
      'bg-destructive/5': 'bg-destructive-subtle',
      'bg-destructive/10': 'bg-destructive-subtle',
      'bg-destructive/20': 'bg-destructive-subtle',
      'bg-success/5': 'bg-success-subtle',
      'bg-success/10': 'bg-success-subtle',
      'bg-success/20': 'bg-success-subtle',
      'bg-warning/5': 'bg-warning-subtle',
      'bg-warning/10': 'bg-warning-subtle',
      'bg-warning/20': 'bg-warning-subtle',
      'bg-info/5': 'bg-info-subtle',
      'bg-info/10': 'bg-info-subtle',
      'bg-info/20': 'bg-info-subtle',
      'border-foreground/20': 'border-border-subtle',
      'border-primary/20': 'border-primary-subtle',
      'border-primary/30': 'border-primary-subtle',
      'border-primary/40': 'border-primary-subtle',
      'border-primary/50': 'border-primary',
      'border-destructive/30': 'border-destructive-subtle',
      'border-destructive/40': 'border-destructive-subtle',
      'border-warning/30': 'border-warning-subtle',
      'ring-primary/20': 'ring-primary-subtle',
      'ring-primary/50': 'ring-primary',
      'ring-ring/50': 'ring-ring',
      'ring-foreground/10': 'ring-border-subtle',
      'shadow-foreground/5': 'shadow-border-subtle',
      'shadow-foreground/15': 'shadow-border-subtle',
      'shadow-primary/10': 'shadow-primary-subtle',
      'bg-accent/50': 'bg-accent',
      'bg-accent/60': 'bg-accent',
      'bg-sidebar-primary/5': 'bg-sidebar-accent',
      'bg-sidebar-accent/50': 'bg-sidebar-accent',
      'via-muted/80': 'via-muted',
      'bg-foreground/25': 'bg-border',
    },
    radius: { rounded: 'rounded-sm', 'rounded-xs': 'rounded-sm' },
    iconSize: { '3': 'xs', '3.5': 's', '4': 'm', '5': 'l' },
    easing: {
      'ease-linear': 'ease-standard',
      'ease-in': 'ease-emphasized',
      'ease-out': 'ease-standard',
      'ease-in-out': 'ease-standard',
      'ease-[cubic-bezier(0.23,1,0.32,1)]': 'ease-standard',
    },
  },
} as const;

export const vendoredUiFiles = [
  'alert-dialog.tsx',
  'badge.tsx',
  'button-group.tsx',
  'button.tsx',
  'calendar.tsx',
  'card.tsx',
  'checkbox.tsx',
  'combobox.tsx',
  'command.tsx',
  'confirm-dialog.tsx',
  'context-menu.tsx',
  'copy-button.tsx',
  'dialog.tsx',
  'dropdown-menu.tsx',
  'empty.tsx',
  'field-error.tsx',
  'input-group.tsx',
  'input.tsx',
  'kbd.tsx',
  'label.tsx',
  'metric-card.tsx',
  'page.tsx',
  'pagination.tsx',
  'popover.tsx',
  'progress.tsx',
  'resizable.tsx',
  'scroll-area.tsx',
  'search-input.tsx',
  'select.tsx',
  'separator.tsx',
  'sheet.tsx',
  'sidebar.tsx',
  'simple-icon.tsx',
  'skeleton.tsx',
  'slider.tsx',
  'sonner.tsx',
  'spinner.tsx',
  'status-dot.tsx',
  'switch.tsx',
  'table.tsx',
  'tabs.tsx',
  'textarea-completions.tsx',
  'textarea.tsx',
  'toggle-group.tsx',
  'toggle.tsx',
  'tooltip.tsx',
] as const;
