#!/usr/bin/env bun
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, relative } from 'path';

import { designTokens, vendoredUiFiles } from '../apps/web/src/styles/tokens.js';

const ROOT = join(import.meta.dir, '..');
const WEB_ROOT = join(ROOT, 'apps/web');
const SOURCE_ROOT = join(WEB_ROOT, 'src');
const GENERATED_HEADER = '// Generated by scripts/check-design-system.ts. Do not edit.\n';
const write = process.argv.includes('--write');
const updateBaseline = process.argv.includes('--update-drift-baseline');

const TAILWIND_CONTAINER_NAMES = new Set([
  '3xs',
  '2xs',
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
  '2xl',
  '3xl',
  '4xl',
  '5xl',
  '6xl',
  '7xl',
]);

function spacingUtilityToken(name: string) {
  const token = `space-${name}`;
  if (TAILWIND_CONTAINER_NAMES.has(token)) {
    throw new Error(`Spacing token "${token}" collides with Tailwind's container scale`);
  }
  return token;
}

function toPosix(path: string) {
  return path.replaceAll('\\', '/');
}

function renderCss() {
  const lines = ['/* Generated by scripts/check-design-system.ts. Do not edit. */', '@theme {'];
  for (const [name, token] of Object.entries(designTokens.spacing)) {
    lines.push(`  --spacing-${spacingUtilityToken(name)}: ${token.value};`);
  }
  lines.push('');
  for (const [name, value] of Object.entries(designTokens.colors)) lines.push(`  --color-${name}: ${String(value)};`);
  lines.push('', '  --ease-*: initial;');
  for (const [name, value] of Object.entries(designTokens.motion.easing))
    lines.push(`  --ease-${name}: ${String(value)};`);
  for (const [name, value] of Object.entries(designTokens.motion.duration))
    lines.push(`  --duration-${name}: ${String(value)};`);
  lines.push('');
  for (const [name, value] of Object.entries(designTokens.iconSize))
    lines.push(`  --size-icon-${name}: ${String(value)};`);
  return `${lines.join('\n')}\n}\n`;
}

function renderToolManifest(vendoredFiles: string[]) {
  const spacingScale = Object.entries(designTokens.spacing)
    .flatMap(([token, definition]) => definition.legacy.map((legacy) => [Number(legacy), spacingUtilityToken(token)]))
    .toSorted(([left], [right]) => Number(left) - Number(right));
  const durationScale = Object.entries(designTokens.motion.duration).map(([token, value]) => [
    Number.parseInt(value),
    token,
  ]);
  const iconSize = Object.entries(designTokens.lint.iconSize).map(([legacy, token]) => [`size-${legacy}`, token]);
  const designSystem = {
    spacing: Object.fromEntries(spacingScale),
    tokenOpacity: designTokens.lint.tokenOpacity,
    radius: designTokens.lint.radius,
    iconSize: designTokens.lint.iconSize,
    primitives: designTokens.primitives,
  };
  const source = `${GENERATED_HEADER}
export const designSystem = ${JSON.stringify(designSystem)};
export const SPACING_SCALE = ${JSON.stringify(spacingScale)};
export const DURATION_SCALE = ${JSON.stringify(durationScale)};
export const RADIUS_REPLACEMENTS = new Map(${JSON.stringify(Object.entries(designTokens.lint.radius))});
export const EASING_REPLACEMENTS = new Map(${JSON.stringify(Object.entries(designTokens.lint.easing))});
export const ICON_SIZE_REPLACEMENTS = new Map(${JSON.stringify(iconSize)});
export const TOKEN_OPACITY_REPLACEMENTS = new Map(${JSON.stringify(Object.entries(designTokens.lint.tokenOpacity))});
export const PRIMITIVE_VARIANTS = ${JSON.stringify(designTokens.primitives)};
export const VENDORED_UI_FILES = ${JSON.stringify(vendoredFiles)};
export const vendoredUiFiles = VENDORED_UI_FILES;
`;
  const formatted = Bun.spawnSync(['bunx', 'oxfmt', '--stdin-filepath', 'design-system.generated.mjs'], {
    cwd: ROOT,
    stdin: Buffer.from(source),
    stdout: 'pipe',
    stderr: 'pipe',
  });
  if (formatted.exitCode !== 0) throw new Error(formatted.stderr.toString());
  return formatted.stdout.toString();
}

function renderPrimitiveManifest() {
  const spacing = Object.keys(designTokens.spacing);
  const source = `${GENERATED_HEADER}
export const stackGapVariants = ${JSON.stringify(Object.fromEntries(spacing.map((token) => [token, `gap-space-${token}`])))} as const;
export const stackPaddingVariants = ${JSON.stringify(Object.fromEntries(spacing.map((token) => [token, `p-${spacingUtilityToken(token)}`])))} as const;
export const stackDirectionVariants = ${JSON.stringify(designTokens.primitives.stack.direction)} as const;
export const stackAlignVariants = ${JSON.stringify(designTokens.primitives.stack.align)} as const;
export const stackJustifyVariants = ${JSON.stringify(designTokens.primitives.stack.justify)} as const;
export const stackWrapVariants = ${JSON.stringify(designTokens.primitives.stack.wrap)} as const;
export const stackGrowVariants = ${JSON.stringify(designTokens.primitives.stack.grow)} as const;
export const stackWidthVariants = ${JSON.stringify(designTokens.primitives.stack.width)} as const;
export const stackHeightVariants = ${JSON.stringify(designTokens.primitives.stack.height)} as const;
export const stackOverflowVariants = ${JSON.stringify(designTokens.primitives.stack.overflow)} as const;
export const textVariantClasses = ${JSON.stringify(designTokens.primitives.text.variant)} as const;
export const textToneClasses = ${JSON.stringify(designTokens.primitives.text.tone)} as const;
export const textAlignClasses = ${JSON.stringify(designTokens.primitives.text.align)} as const;
export const textLineClampClasses = ${JSON.stringify(designTokens.primitives.text.lineClamp)} as const;
export const iconSizeClasses = ${JSON.stringify(Object.fromEntries(Object.keys(designTokens.iconSize).map((token) => [token, `size-icon-${token}`])))} as const;
`;
  const formatted = Bun.spawnSync(['bunx', 'oxfmt', '--stdin-filepath', 'tokens.generated.ts'], {
    cwd: ROOT,
    stdin: Buffer.from(source),
    stdout: 'pipe',
    stderr: 'pipe',
  });
  if (formatted.exitCode !== 0) throw new Error(formatted.stderr.toString());
  return formatted.stdout.toString();
}

function listTsxFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) return listTsxFiles(path);
    return entry.name.endsWith('.tsx') ? [path] : [];
  });
}

function getVendoredUiFiles() {
  const files = vendoredUiFiles.map((file) => `apps/web/src/components/ui/${file}`);
  const missing = files.filter((file) => !existsSync(join(ROOT, file)));
  if (missing.length > 0) throw new Error(`Missing vendored UI files:\n${missing.join('\n')}`);
  return files;
}

const generatedFiles = new Map([
  [join(SOURCE_ROOT, 'styles/tokens.generated.css'), renderCss()],
  [join(SOURCE_ROOT, 'styles/tokens.generated.ts'), renderPrimitiveManifest()],
  [join(ROOT, 'tools/oxlint-plugins/ui/design-system.generated.mjs'), renderToolManifest(getVendoredUiFiles())],
]);

const normalizeNewlines = (content: string) => content.replaceAll('\r\n', '\n');
const stale = [...generatedFiles].filter(
  ([path, content]) =>
    !existsSync(path) || normalizeNewlines(readFileSync(path, 'utf8')) !== normalizeNewlines(content),
);
if (write) {
  for (const [path, content] of generatedFiles) writeFileSync(path, content);
} else if (stale.length > 0) {
  console.error('Generated design-system files are stale:');
  for (const [path] of stale) console.error(`  ${toPosix(relative(ROOT, path))}`);
  console.error('Run: bun run scripts/check-design-system.ts --write');
  process.exit(1);
}

const UTILITY = String.raw`[^\s"'\x60}]+`;
const typographyTokens =
  /^(?:text-(?:2xs|xs|sm|base|lg|xl|2xl|foreground|muted-foreground)|font-(?:normal|medium|semibold|bold|mono)|tracking-[^\s]+|leading-[^\s]+)$/;
const normalizedSpacing = new Map(
  Object.entries(designTokens.spacing).flatMap(([token, definition]) => [
    [token, token],
    [spacingUtilityToken(token), token],
    ...definition.legacy.map((legacy) => [legacy, token]),
  ]),
);

function matches(source: string, pattern: RegExp) {
  return new Set([...source.matchAll(pattern)].map((match) => match[1]));
}

function collectDrift(files: string[]) {
  const axes = {
    tokenOpacity: new Set<string>(),
    typography: new Set<string>(),
    iconSize: new Set<string>(),
    spacing: new Set<string>(),
    radius: new Set<string>(),
    motion: new Set<string>(),
  };
  for (const file of files) {
    const source = readFileSync(file, 'utf8');
    for (const value of matches(
      source,
      new RegExp(String.raw`\b(?:bg|text|border|divide|ring|outline|shadow)-(${UTILITY}\/\d+)`, 'g'),
    ))
      axes.tokenOpacity.add(value);
    for (const value of matches(source, /\bsize-([\d.]+)\b/g)) axes.iconSize.add(value);
    for (const value of matches(
      source,
      new RegExp(String.raw`\b(?:[mp][trblxy]?|gap(?:-[xy])?|space-[xy])-(${UTILITY})`, 'g'),
    ))
      axes.spacing.add(normalizedSpacing.get(value) ?? value);
    for (const value of matches(source, new RegExp(String.raw`\b(rounded(?:-${UTILITY})?)`, 'g')))
      axes.radius.add(value);
    for (const value of matches(source, new RegExp(String.raw`\b((?:duration|ease)-${UTILITY})`, 'g')))
      axes.motion.add(value);
    for (const element of source.matchAll(/<(?:p|span)\b[^>]*>/gs)) {
      const tokens = element[0].match(/[^\s"'`{}]+/g)?.filter((token) => typographyTokens.test(token)) ?? [];
      if (tokens.length > 0) axes.typography.add([...new Set(tokens)].toSorted().join(' '));
    }
  }
  return Object.fromEntries(Object.entries(axes).map(([axis, values]) => [axis, values.size]));
}

const allFiles = listTsxFiles(SOURCE_ROOT);
const vendoredFileSet = new Set(getVendoredUiFiles());
const drift = {
  app: collectDrift(allFiles.filter((path) => !vendoredFileSet.has(toPosix(relative(ROOT, path))))),
  vendoredUi: collectDrift(allFiles.filter((path) => vendoredFileSet.has(toPosix(relative(ROOT, path))))),
};
const baselinePath = join(SOURCE_ROOT, 'styles/design-system-drift-baseline.json');
if (updateBaseline) {
  writeFileSync(baselinePath, `${JSON.stringify(drift, null, 2)}\n`);
} else {
  if (!existsSync(baselinePath)) {
    console.error(
      'Missing design-system drift baseline. Run: bun run scripts/check-design-system.ts --update-drift-baseline',
    );
    process.exit(1);
  }
  const baseline = JSON.parse(readFileSync(baselinePath, 'utf8')) as typeof drift;
  const regressions = Object.entries(drift).flatMap(([scope, axes]) =>
    Object.entries(axes).flatMap(([axis, count]) => {
      const budget = baseline[scope as keyof typeof baseline][axis as keyof typeof axes];
      return count > budget ? [`${scope}.${axis}: ${count} > ${budget}`] : [];
    }),
  );
  if (regressions.length > 0) {
    console.error('Design-system drift budget exceeded:');
    for (const regression of regressions) console.error(`  ${regression}`);
    process.exit(1);
  }
}

console.log(`Design-system generation and drift budget are current (${vendoredUiFiles.length} vendored UI files).`);
